"""
Hacks required to get Quart to do what I want it to do.
"""
from typing import Callable, Awaitable, Coroutine
from hypercorn import Config as HyperConfig
from hypercorn.asyncio import serve
from quart import Quart
from quart.routing import QuartMap, MapAdapter


__all__ = ['PrefixedQuartMap', 'PatchedQuart']


class PrefixedQuartMap(QuartMap):
    """
    This hack allows you to prefix all outgoing URLs generated by url_for() without changing incoming URLs used in routing.
    Example usage:

    ```
    quart.Quart.url_map_class = PrefixedQuartMap
    app = quart.Quart(__name__)
    app.url_map.url_prefix = '/myprefix'
    ```
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.url_prefix = ''

    def bind_to_request(self, request, subdomain, server_name) -> MapAdapter:
        """This method is defined in quart.QuartMap."""
        adapter = super().bind_to_request(request, subdomain, server_name)
        adapter.script_name = self.url_prefix + adapter.script_name
        return adapter

    def bind_to_environ(self, environ, server_name=None, subdomain=None) -> MapAdapter:
        adapter = super().bind_to_environ(environ, server_name, subdomain)
        adapter.script_name = self.url_prefix + adapter.script_name
        return adapter


class PatchedQuart(Quart):
    """Patched Quart class that does things the way I want it to do things."""
    url_map_class = PrefixedQuartMap

    def run_task(
            self,
            host: str = "127.0.0.1",
            port: int = 5000,
            debug: bool | None = None,
            ca_certs: str | None = None,
            certfile: str | None = None,
            keyfile: str | None = None,
            shutdown_trigger: Callable[..., Awaitable[None]] | None = None,
            startup_timeout: float | None = None,
            shutdown_timeout: float | None = None,
    ) -> Coroutine[None, None, None]:
        """Replacement for a built-in run-task() that lets me specify timeouts."""
        config = HyperConfig()
        config.access_log_format = "%(h)s %(r)s %(s)s %(b)s %(D)s"
        config.accesslog = "-"
        config.bind = [f"{host}:{port}"]
        config.ca_certs = ca_certs
        config.certfile = certfile
        if debug is not None:
            self.debug = debug
        if startup_timeout is not None:
            config.startup_timeout = startup_timeout
        if shutdown_timeout is not None:
            config.shutdown_timeout = shutdown_timeout
        config.errorlog = config.accesslog
        config.keyfile = keyfile

        return serve(self, config, shutdown_trigger=shutdown_trigger)
